### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by Agheb** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#16]
Goal: A document to help you make your first contribution here.

Topics we could include:
- How to submit Pull Requests
- Quality Standards (scope, submission should be useful for community)
- Markdown Standards 
and so on 

Any ideas and or suggestions?

**Comment by Stefan0x** [comment]
That is what I did for the past hour since I'm entirely new to the contribution side if GitHub.
But because of that, I had to research how to do it. Here is my suggestion how to explain it to Newbies like me:

1. Create a personal fork of the project on Github via the button on the top right.
2. Clone the fork on your local machine via Terminal
`git clone https://github.com/[your_username]/awesome-google-mobile-web-challenge-links-2017`
3. Edit your changes locally
4. Push your branch to your fork on Github via Terminal
`git add .`
`git push master`
5. From **your fork** open a pull request.

I hope that is what you meant. Did I miss something?

**Comment by Agheb** [comment]
@euchenhofer Yes, something just like this. A short and concise guide to get started right away.

**Comment by Agheb** [comment]
We could mention the following udacity courses in the guide too:
* [How to use GIT and Github](https://www.udacity.com/course/how-to-use-git-and-github--ud775)
* [Writing READMEs](https://www.udacity.com/course/writing-readmes--ud777)

**Comment by Agheb** [comment]
@euchenhofer Would you be interested to team up with me on this ?

**Comment by Stefan0x** [comment]
Sure. I'd like that. :-) A great idea to mention the courses.

**Comment by adomanskagrzyb** [comment]
Sounds awesome, thank you guys! I was also wondering - maybe we could at some point add templates for creating pull request and issue request https://help.github.com/articles/setting-guidelines-for-repository-contributors/? What do you think about that?

**Comment by adomanskagrzyb** [comment]
Btw because this `Thanks to contributors` part appeared, I would also add info that if you are creating pull request (or contributing in any other way) and your name is not there, you are welcome to add yourself (just let's stick to alphabetical order).

**Comment by adomanskagrzyb** [comment]
ok, I created a raw draft on [how to contribute](https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/blob/master/contributing.md), it would be good to 1. polish it (few more words on the beginning + better text formatting), 2. add more content (things that we discussed here and additional instructions like how to create pull request etc) 3. add a right flow? regarding our [previous discussion](https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/issues/17) - should we stick to submissions via Github issue tracker? if so, then we don't need info on how to create a pull request, commit message etc

**Comment by Stefan0x** [comment]
Thank you @DomanskaGrzyb for creating the file. I added some content and styling. It is still in draft mode and I'll have to make some further learning myself. I definitely violated the guidelines while working on the guidelines. I hope you can forgive me. ;)
About the submissions: Since this is a repo for a learning course I suggest that we allow submissions via issue tracker and via pull requests. So everyone can learn the most from it.
@Agheb What do you think about the structure? Would you further define the markdown standards or just link to articles? What is missing?

**Comment by Agheb** [comment]
totally agree with you about submissions. 

In general, I would like to keep it brief and to the point. Some sections like the git commit style are too detailed for my taste.

I'm going to add some quality standards like this: 
- Make sure your suggestion is not a duplicate
- Check your spelling and grammar
- Strive for Quality, Not Quantity/Less is more 
- Explain in a few words why you think your submission is awesome/useful to the community

**Comment by Agheb** [comment]
and it is considered bad practice to name your PRs `Update README.md`. We should mention some good examples that we would like to see
